#!/usr/bin/bash

set -eoux pipefail

# unfortunately this is bugged on ... TBD
firmware="mt7xxx-firmware"
dnf5 -y remove --no-autoremove $firmware
dnf5 -y install --repo="copr:copr.fedorainfracloud.org:bazzite-org:bazzite" $firmware
